
NUMBER_OF_ROUNDS = 6
NUMBER_OF_CARDS = 10
CARDS_IN_HAND = 4
INITAL_DRAW = 4
REWARD_REDUCTION = 0

DEFAULT_TOTAL_ITERATIONS = 500
DEFAULT_MODE = ""
LEARNING_RATE = 0.005
DISCOUNT_FACTOR = 1
DEFAULT_NETWORK_WIDTH = 200
DEFAULT_NETWORK_DEPTH = 3
BATCH_SIZE = 80
